from agents.agent_1_sentiment import SentimentAgent
from agents.agent_2_technical import TechnicalAgent
from agents.agent_3_fundamental import FundamentalAgent
from agents.agent_4_macro import MacroAgent
from agents.agent_5_judge import JudgeAgent
from agents.agent_6_synthesis import SynthesisAgent
from agents.agent_8_auditor import PredictionAuditorAgent
from agents.agent_7_portfolio import PortfolioManager
